### PR TITLE
Created the Global css files for standard stylings in the Website.

### LINKED ISSUE #36: Create global css for standard stylings.
**Describe the bug**
Create global css for standard stylings

### PR DESCRIPTION
**Pull request by ritankarsaha**
Fixes #36 
Created Global CSS Files for Standard Stylings in the Website.

### Features added in the styles.scss file:-

-Root Variables: Defines color, font sizes, and other constants for easier updates.
-Typography: Improved styling for headings (h1 to h6) and paragraphs (p).
-Responsive Font Size: Uses @media queries to adjust font size based on screen width.
-Links and Buttons: Added hover effects and color transitions for interactive elements.
-Form Styling: Ensures that input fields, text areas, and selects have a consistent style and focus effect.
-Root Variables:
Colors (--primary-color, --secondary-color, etc.), spacing, font sizes, and line heights have been defined as reusable variables for easy maintenance.
-Dark Mode Support:
Using data-theme='dark', you can toggle a dark mode theme by changing the background and text colors dynamically. Add data-theme="dark" to the <body> tag when needed.
-Utility Classes:
Margin and padding classes (mt-1, mb-2, etc.), text alignment (text-center, text-left, etc.), and flexbox utilities (flex, justify-center, etc.) for fast prototyping and layout adjustments.
-Grid System:
A simple CSS grid layout system with predefined column options (e.g., grid-cols-2, grid-cols-3). These can help you create flexible layouts with minimal effort.
-Media Queries:
Adjusted base font sizes and element sizes for responsiveness on screens smaller than 768px (tablets and mobiles).

Using Dark Mode: To enable dark mode, add data-theme="dark" to the <body> element. You can use JavaScript to toggle this dynamically if needed.

Grid Layout: Apply the .grid and .grid-cols-* classes to elements where you want a grid layout. You can customize the number of columns as needed.

Utility Classes: Use the utility classes like .flex, .justify-center, .mt-2, and .text-center to quickly style components without needing additional CSS.

### Features added in the app-components.scss:-

-Reset styles: To standardize margins, paddings, and box-sizing across browsers.
-Body: Global styles for the body, setting a clean base for the entire application.
-Headings and paragraphs: Styles for headings and paragraphs for uniformity.
-Links: Simple styles for links with hover effects.
-Buttons: A reusable button style with a hover effect.
-Flex utilities: Handy classes to quickly implement flexbox layouts.
-Spacing utilities: Classes like .mt-1, .mb-2 for margin adjustments.
-Responsive design: Media queries to adjust layout for smaller screen sizes.
-Form Elements: Stylized input fields, textareas, and select boxes with focus effects.
-Table Styling: Clean table design with alternating row colors and a structured layout.
-Grid System: Responsive 12-column grid for easy layout creation.
-Flex Utilities: Predefined classes for flexbox layouts such as .flex, .flex-center, .flex-column.
-Card Styles: Custom card design with shadow effects for modern UI components.
-Animations: Simple fade-in effect for smooth content transitions.
-Dark Mode Support: Global dark mode styles for the entire website (trigger with the .dark-mode class on body).
-Spinners: A spinner component for loading animations.
-Responsive Design: Updated media queries to ensure layouts adjust smoothly on smaller screens.

I have made the necessary changes in the global css files for standard stylings in the website.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests have passed and it does not give any unexpected error for the same.

### CODE REVIEW

**Comment by ritankarsaha** [comment]
I have created the global css files for standard stylings in the website. Please let me know if any more modifications/additions are required. I have done all modifications extensively and I hope this global css would be enough for making standard stylings in this website.

**Comment by rajutkarsh07** [comment]
Add screenshot/video if it is working fine or not

**Comment by ritankarsaha** [comment]
Screenshot 2024-10-16 at 4 26 38 AM


Screenshot 2024-10-16 at 4 26 18 AM

The website is working fine and the global css file is ready to use in the project for standard stylings.

**Comment by rajutkarsh07** [comment]
Every navigation element with their icons are not centred so fix that
I think all the other things are fine 
Record a video showing all the changes that will be better 
Then I will merge it

**Comment by rajutkarsh07** [comment]
Every navigation element with their icons are not centred so fix that
I think all the other things are fine 
Record a video showing all the changes that will be better 
Then I will merge it

**Comment by ritankarsaha** [comment]
> Every navigation element and buttons with their icons are not centred so fix that
> I think all the other things are fine 
> Record a video showing all the changes that will be better 
> Then I will merge it 

Sure will do it. Thank you.

**Comment by ritankarsaha** [comment]
@rajutkarsh07 Are any more changes required in the PR?

**Comment by rajutkarsh07** [comment]
image
make buttons text center aligned both vertical and horizontal
image
on hover the text color must change in the navbar and it should also be center aligned both vertical and horizontal

**Comment by ritankarsaha** [comment]
@rajutkarsh07  Should I work on this issue still or will you be looking after the PR now, as you self assigned this, I am not sure could you please tell?

**Comment by rajutkarsh07** [comment]
@ritankarsaha it's by mistake(i was actually not getting notification that's why I was assigning my self as reviewers) 
just complete the things I have said I will merge

**Comment by ritankarsaha** [comment]
> @ritankarsaha it's by mistake(i was actually not getting notification that's why I was assigning my self as reviewers) 
> just complete the things I have said I will merge

Oh sure @rajutkarsh07

**Comment by ritankarsaha** [comment]
> > @ritankarsaha it's by mistake(i was actually not getting notification that's why I was assigning my self as reviewers)
> > just complete the things I have said I will merge
> 
> Oh sure @rajutkarsh07

@rajutkarsh07 Made the necessary changes.

**Comment by rajutkarsh07** [comment]
still the alignment is not fixed in both the buttons and navbar elements with the hover effect 
and remove the comments that you have generated using chatgpt

**Comment by rajutkarsh07** [comment]
@ritankarsaha just update the changes I will merge

**Comment by ritankarsaha** [comment]
> @ritankarsaha just update the changes I will merge

yes sir

**Comment by ritankarsaha** [comment]
Screenshot 2024-10-31 at 1 05 28 PM


Made the necessary changes as asked. Thank You

**Pull request merged**
