### PR TITLE
Dark Mode added

### PR DESCRIPTION
**Pull request by sakshamgupta912**
## Description
Added a dark mode option to the application, providing a darker color scheme for improved usability in low-light environments. This mode can be toggled manually or automatically based on system settings.

## Related Issue
[Issue #100](https://github.com/c2siorg/Webiu/issues/100)

## Motivation and Context
The bright interface of the application causes eye strain and discomfort during extended use in low-light environments. Dark mode helps alleviate this issue, improves usability in nighttime settings, and conserves battery life on OLED devices.

## Screen recording:

https://github.com/user-attachments/assets/23661fb8-203b-4d65-8c45-f92759a7700a

## Screenshots (In case of UI changes):
# Dark Mode and Light Mode Screenshots

## Home Page
- **Dark Mode:**
  Home Page Dark Mode
- **Light Mode:**
  Home Page Light Mode

## Projects Page
- **Dark Mode:**
  Projects Page Dark Mode
- **Light Mode:**
  Projects Page Light Mode

## Publications Page
- **Dark Mode:**
  Publications Page Dark Mode
- **Light Mode:**
  Publications Page Light Mode

## Community Page
- **Dark Mode:**
  Community Page Dark Mode
- **Light Mode:**
  Community Page Light Mode

## Contributors Page
- **Dark Mode:**
  Contributors Page Dark Mode
- **Light Mode:**
  Contributors Page Light Mode

## Project Ideas Page
- **Dark Mode:**
  Project Ideas Page Dark Mode
- **Light Mode:**
  Project Ideas Page Light Mode

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests have passed and it does not give any unexpected error for the same.

### CODE REVIEW

**Comment by rajutkarsh07** [comment]
Hi @sakshamgupta912,  

The pages are looking great! However, could you please do the following tweaks:  
1. Match the colors across all pages with the design file: [Webiu Prototype Figma Design](https://www.figma.com/design/HOl7SsZSe8nejRNuw8JMjI/webiu-prototype?node-id=294-1379&m=dev).  
2. For the **Project** page, remove the white background and the border.  
3. For the **Publication** page, add a good background.  
4. and match all the pages with this color scheme

Let me know if you need any clarification. Thanks!

**Comment by sakshamgupta912** [comment]
@rajutkarsh07 default mode is light mode rn

**Comment by sakshamgupta912** [comment]
> Update the screenshot of the projects page

@rajutkarsh07 Kindly check the previous comment, i have updated the screen short

**Comment by rajutkarsh07** [comment]
Update the project page also 🥲

**Comment by rajutkarsh07** [comment]
Remove the white borders, white background 
Update the background only

**Pull request merged**
